import { redirect } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import { createClient } from "@/lib/supabase/server";
import { listRadars } from "@/lib/radar/data";
import { chooseCoverage } from "@/lib/radar/states";
import { RadarCard } from "@/components/radar/RadarCard";
import { CoverageNotice } from "@/components/radar/CoverageNotice";
import { RadarStateBlock } from "@/components/radar/RadarStateBlock";
import { Button } from "@/components/ui/button";
export const metadata:Metadata={title:"Kèo Radar - CheckBDS.online",robots:{index:false,follow:false}};
export default async function RadarPage(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login?next=/radar");let radars;try{radars=await listRadars(s,user.id);}catch{return <main className="min-h-screen bg-cream"><div className="mx-auto max-w-[1120px] px-5 py-10"><RadarStateBlock kind="error"/></div></main>;}const coverage=chooseCoverage(radars.map(r=>r.coverage));return <main className="min-h-screen bg-cream"><header className="sticky top-0 z-30 border-b border-white/10 bg-navy/90 backdrop-blur-xl"><div className="mx-auto flex h-[64px] max-w-[1120px] items-center justify-between gap-3 px-5 md:px-8"><Link href="/dashboard" className="inline-flex min-h-12 items-center text-small font-semibold text-white">Dashboard</Link><div className="flex items-center gap-3"><span className="hidden sm:inline text-micro font-bold tracking-[0.18em] text-gold-soft">KÈO RADAR</span><Link href="/radar/new"><Button size="lg" className="h-12 bg-gold-base px-4 text-navy">+ Tạo Radar</Button></Link></div></div></header><div className="mx-auto max-w-[1120px] px-5 py-10 md:px-8"><div className="mb-6"><p className="text-micro font-semibold uppercase tracking-[0.18em] text-gold-ink">KÈO RADAR</p><h1 className="mt-1 text-h2 text-navy">Tự tìm tin khớp tiêu chí</h1><p className="mt-2 text-lead text-ink-600">Đặt tiêu chí, CheckBDS tự tìm tin khớp.</p></div>{coverage&&<div className="mb-5"><CoverageNotice coverage={coverage}/></div>}{radars.length===0?<RadarStateBlock kind="empty"/>:<div className="grid min-w-0 gap-4 lg:grid-cols-2">{radars.map(r=><RadarCard key={r.id} radar={r}/>)}</div>}</div></main>;}