"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2,RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CoverageNotice } from "./CoverageNotice";
import { MatchCard } from "./MatchCard";
import { DataSourcePanel } from "./DataSourcePanel";
import { FreshnessStamp } from "./FreshnessStamp";
import type { RadarMatch,RadarSummary } from "@/lib/radar/types";
import { COPY } from "@/lib/radar/states";
import { criteriaSummary } from "@/lib/radar/format";
export function RadarDetailClient({radar,initialMatches}:{radar:RadarSummary;initialMatches:RadarMatch[]}){const router=useRouter();const[scanning,setScanning]=useState(!radar.coverage.checkedAt);const[error,setError]=useState<string|null>(null);useEffect(()=>{if(!radar.coverage.checkedAt)void scan();},[]);async function scan(){setScanning(true);setError(null);try{const r=await fetch("/api/radars/"+radar.id+"/scan",{method:"POST"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Không quét được dữ liệu Radar.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Không quét được dữ liệu Radar.");}finally{setScanning(false);}}const noMatch=!scanning&&(radar.lastScanCount??0)===0;return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div className="min-w-0"><p className="text-micro font-semibold uppercase tracking-[0.18em] text-gold-ink">KÈO RADAR</p><h1 className="mt-1 text-h2 text-navy">{radar.name}</h1><p className="mt-2 text-small text-ink-600">{criteriaSummary(radar)}</p></div><div className="flex items-center gap-2"><FreshnessStamp freshness={radar.coverage.freshness}/><Button type="button" size="lg" variant="outline" onClick={()=>void scan()} disabled={scanning}>{scanning&&<Loader2 className="h-4 w-4 animate-spin"/>}<RefreshCw className="h-4 w-4"/>{scanning?"Đang quét…":"Quét lại"}</Button></div></div><CoverageNotice coverage={radar.coverage}/>{error&&<div role="alert" className="rounded-lg border border-risk-high/30 bg-risk-high-wash p-4 text-small text-risk-high">{error}</div>}{scanning&&!radar.coverage.checkedAt?<div className="grid gap-4" aria-busy="true">{[1,2,3].map(i=><div key={i} className="h-44 animate-pulse rounded-lg border border-line bg-surface"/>)}<p className="text-small text-ink-600">Đang khởi động Radar…</p></div>:noMatch?<div className="rounded-lg border border-line bg-surface p-5"><h2 className="text-h3 text-navy">{COPY.noMatch(radar.lastScanCount??0).title}</h2><p className="mt-2 text-small text-ink-600">{COPY.noMatch(radar.lastScanCount??0).body}</p><a href={"/radar/"+radar.id+"/edit"} className="mt-4 inline-flex text-small font-semibold text-navy underline underline-offset-2">Sửa tiêu chí</a></div>:<div className="grid min-w-0 gap-4 lg:grid-cols-2">{initialMatches.map(m=><MatchCard key={m.externalId} match={m}/>)}</div>}<DataSourcePanel coverage={radar.coverage}/></div>;}