"use client";
import { useMemo,useState } from "react";
import { Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CATEGORY_LABEL } from "@/lib/price/scope";
import { validateRadarInput,type RadarFieldError } from "@/lib/radar/criteria";
import { NGO_P_STRONG_THRESHOLD } from "@/lib/radar/signals";
import type { RadarAreaOption,RadarCoverage,RadarSummary } from "@/lib/radar/types";
import { FormField } from "./FormField";
import { PairField } from "./PairField";
import { ErrorSummary } from "./ErrorSummary";
import { CoverageNotice } from "./CoverageNotice";

function toVnd(raw:string){if(!raw.trim())return null;const n=Number(raw.trim().replace(",","."));return Number.isFinite(n)?Math.round(n*1_000_000_000):null;}
function fromVnd(v:number|null){return v==null?"":String(v/1_000_000_000).replace(/\.0+$/,"");}
const DEALS=[["ngop_ngon","Kèo ngộp ngon"],["thom_dau_tu","Tiềm năng cao"],["gia_cao","Giá cao hơn TT"],["rui_ro_phap_ly","Rủi ro pháp lý"],["binh_thuong","Bình thường"]];
export function RadarForm({areas,initial}:{areas:RadarAreaOption[];initial?:RadarSummary|null}){const router=useRouter();const[name,setName]=useState(initial?.name??"");const[areaV2,setAreaV2]=useState(initial?String(initial.areaV2):"");const[categoryCode,setCategoryCode]=useState(initial?.categoryCode==null?"":String(initial.categoryCode));const[priceMin,setPriceMin]=useState(fromVnd(initial?.priceMinVnd??null));const[priceMax,setPriceMax]=useState(fromVnd(initial?.priceMaxVnd??null));const[areaMin,setAreaMin]=useState(initial?.areaMinM2==null?"":String(initial.areaMinM2));const[areaMax,setAreaMax]=useState(initial?.areaMaxM2==null?"":String(initial.areaMaxM2));const[minScore,setMinScore]=useState(initial?.minScore==null?"":String(initial.minScore));const[dealTypes,setDealTypes]=useState<string[]>(initial?.dealTypes??[]);const[ngoPOnly,setNgoPOnly]=useState(initial?.ngoPOnly??false);const[errors,setErrors]=useState<Partial<Record<RadarFieldError,string>>>({});const[serverError,setServerError]=useState<string|null>(null);const[coverage,setCoverage]=useState<RadarCoverage|null>(null);const[busy,setBusy]=useState(false);const selected=useMemo(()=>areas.find(a=>String(a.areaV2)===areaV2),[areas,areaV2]);
async function loadCoverage(v:string){setAreaV2(v);if(!v){setCoverage(null);return;}try{const r=await fetch("/api/radars/coverage?areaV2="+encodeURIComponent(v));const d=await r.json();setCoverage(d.coverage??null);}catch{setCoverage(null);}}
function validate(){const v=validateRadarInput({name,areaV2,areaName:selected?.areaName,regionName:selected?.regionName,categoryCode,priceMinVnd:toVnd(priceMin),priceMaxVnd:toVnd(priceMax),areaMinM2:areaMin,areaMaxM2:areaMax,minScore:minScore||null,dealTypes,ngoPOnly,status:initial?.status??"ACTIVE"});setErrors(v.errors);return v;}
function blur(field:RadarFieldError){const v=validate();if(v.errors[field])setErrors(x=>({...x,[field]:v.errors[field]}));}
async function submit(){setServerError(null);const v=validate();if(!v.ok||!v.value){const first=Object.keys(v.errors)[0];if(first)document.getElementById(first==="price"?"priceMin":first==="area"?"areaMin":first)?.focus();return;}setBusy(true);try{const url=initial?"/api/radars/"+initial.id:"/api/radars";const r=await fetch(url,{method:initial?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(v.value)});const d=await r.json().catch(()=>({}));if(!r.ok){setServerError(d.error??"Không lưu được Radar.");setErrors(d.fieldErrors??{});return;}router.push("/radar/"+(d.id??initial?.id));}catch{setServerError("Không tạo được Radar. Kiểm tra kết nối rồi thử lại.");}finally{setBusy(false);}}
return <form onSubmit={e=>{e.preventDefault();void submit();}} className="pb-28 md:pb-0">{serverError&&<div role="alert" className="mb-4 rounded-lg border border-risk-high/30 bg-risk-high-wash p-4 text-small text-risk-high">{serverError} <button type="button" className="underline" onClick={()=>void submit()}>Thử lại</button></div>}<ErrorSummary errors={errors}/><div className="mt-4 space-y-6 rounded-panel border border-line bg-surface p-5 shadow-light">
<FormField id="name" label="Tên Radar" error={errors.name}><Input id="name" value={name} maxLength={60} placeholder="Nhà phố Hải Châu" onChange={e=>setName(e.target.value)} onBlur={()=>blur("name")} aria-invalid={Boolean(errors.name)}/></FormField>
<FormField id="areaV2" label="Khu vực" error={errors.areaV2} hint="Coverage cập nhật ngay khi đổi khu vực."><select id="areaV2" value={areaV2} onChange={e=>void loadCoverage(e.target.value)} onBlur={()=>blur("areaV2")} aria-invalid={Boolean(errors.areaV2)} className="h-12 w-full rounded-md border border-line bg-white px-3 text-body text-navy">{!areaV2&&<option value="">Chọn khu vực</option>}{areas.map(a=><option key={a.areaV2} value={a.areaV2}>{a.areaName}, {a.regionName}</option>)}</select></FormField>
{coverage&&<CoverageNotice coverage={coverage} size="inline"/>}
<FormField id="categoryCode" label="Loại BĐS"><select id="categoryCode" value={categoryCode} onChange={e=>setCategoryCode(e.target.value)} className="h-12 w-full rounded-md border border-line bg-white px-3 text-body text-navy"><option value="">Mọi loại BĐS</option>{Object.entries(CATEGORY_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></FormField>
<PairField legend="Khoảng giá" error={errors.price}><Input id="priceMin" inputMode="decimal" value={priceMin} placeholder="Tối thiểu · tỷ" aria-label="Giá tối thiểu, tỷ" onChange={e=>setPriceMin(e.target.value)} onBlur={()=>blur("price")}/><Input id="priceMax" inputMode="decimal" value={priceMax} placeholder="Tối đa · tỷ" aria-label="Giá tối đa, tỷ" onChange={e=>setPriceMax(e.target.value)} onBlur={()=>blur("price")}/></PairField>
<PairField legend="Diện tích" error={errors.area}><Input id="areaMin" inputMode="decimal" value={areaMin} placeholder="Tối thiểu · m²" aria-label="Diện tích tối thiểu" onChange={e=>setAreaMin(e.target.value)} onBlur={()=>blur("area")}/><Input id="areaMax" inputMode="decimal" value={areaMax} placeholder="Tối đa · m²" aria-label="Diện tích tối đa" onChange={e=>setAreaMax(e.target.value)} onBlur={()=>blur("area")}/></PairField>
<FormField id="minScore" label="Điểm CheckBDS tối thiểu"><Input id="minScore" type="number" min={0} max={100} value={minScore} onChange={e=>setMinScore(e.target.value)}/><p className="mt-1 text-micro italic text-ink-600">Chỉ áp dụng cho tin đã chấm điểm. Tin chưa chấm vẫn luôn hiện.</p></FormField>
<FormField id="dealTypes" label="Loại kèo"><div className="grid gap-2 sm:grid-cols-2">{DEALS.map(([v,l])=><label key={v} className="flex min-h-12 items-center gap-2 rounded-md border border-line px-3 text-small text-ink-700"><input type="checkbox" checked={dealTypes.includes(v)} onChange={e=>setDealTypes(p=>e.target.checked?[...p,v]:p.filter(x=>x!==v))}/>{l}</label>)}</div><p className="mt-1 text-micro italic text-ink-600">Bỏ trống nghĩa là hiện mọi loại kèo. Chỉ áp dụng cho tin đã chấm điểm.</p></FormField>
<FormField id="ngoPOnly" label="Dấu hiệu bán gấp"><label className="flex min-h-12 items-center gap-2 rounded-md border border-line px-3 text-small text-ink-700"><input type="checkbox" checked={ngoPOnly} onChange={e=>setNgoPOnly(e.target.checked)}/>Chỉ hiển thị tin có dấu hiệu bán gấp</label><p className="mt-1 text-micro italic text-ink-600">Giữ tin có điểm Ngộp trên {NGO_P_STRONG_THRESHOLD}. Tin chưa chấm vẫn luôn hiện.</p></FormField>
</div><div className="mt-4"><Button type="button" variant="outline" size="lg" onClick={()=>router.back()}>Huỷ</Button></div><div className="fixed inset-x-0 bottom-0 z-30 border-t border-line bg-cream/95 p-3 pb-[calc(12px+env(safe-area-inset-bottom))] backdrop-blur md:static md:mt-4 md:border-0 md:bg-transparent md:p-0 md:backdrop-blur-none"><Button type="submit" size="lg" disabled={busy} className="w-full bg-gold-base text-navy hover:bg-gold-base/90 md:w-auto">{busy&&<Loader2 className="h-4 w-4 animate-spin" aria-hidden/>}{busy?(initial?"Đang lưu…":"Đang tạo…"):(initial?"Lưu thay đổi":"Tạo Radar")}</Button></div></form>;}