// 63 tỉnh/thành Việt Nam + nhận diện khu vực từ nội dung tin rao

export const PROVINCES = [
  "Hà Nội",
  "Hồ Chí Minh",
  "Hải Phòng",
  "Đà Nẵng",
  "Cần Thơ",
  "Biên Hòa",
  "Nha Trang",
  "Huế",
  "Vũng Tàu",
  "Quảng Ninh",
  "Hạ Long",
  "Hải Dương",
  "Thanh Hóa",
  "Nghệ An",
  "Bình Dương",
  "Đồng Nai",
  "Bắc Ninh",
  "Hà Giang",
  "Lào Cai",
  "Cao Bằng",
  "Bắc Kạn",
  "Tuyên Quang",
  "Lạng Sơn",
  "Quảng Trị",
  "Quảng Nam",
  "Quảng Ngãi",
  "Bình Định",
  "Phú Yên",
  "Đắk Lắk",
  "Đắk Nông",
  "Gia Lai",
  "Kon Tum",
  "Bình Phước",
  "Tây Ninh",
  "Long An",
  "Tiền Giang",
  "Bến Tre",
  "Trà Vinh",
  "Vĩnh Long",
  "Sóc Trăng",
  "An Giang",
  "Kiên Giang",
  "Cà Mau",
  "Bạc Liêu",
  "Hậu Giang",
  "Đồng Tháp",
  "Vĩnh Phúc",
  "Hòa Bình",
  "Phú Thọ",
  "Tuyên Quang",
  "Lai Châu",
  "Sơn La",
  "Điện Biên",
  "Yên Bái",
  "Bắc Giang",
  "Bắc Ninh",
  "Hà Tĩnh",
  "Quảng Trạch",
  "Thanh Hà",
] as const;

export type Province = (typeof PROVINCES)[number];

// Từ khoá nhận diện trong tin rao (lowercase) -> tên tỉnh hiển thị
const ALIASES: { key: string; label: string }[] = [
  { key: "ha noi", label: "Hà Nội" },
  { key: "hà nội", label: "Hà Nội" },
  { key: "ho chi minh", label: "TP.HCM" },
  { key: "hồ chí minh", label: "TP.HCM" },
  { key: "sai gon", label: "TP.HCM" },
  { key: "sài gòn", label: "TP.HCM" },
  { key: "thu duc", label: "TP.HCM" },
  { key: "binh thanh", label: "TP.HCM" },
  { key: "go vap", label: "TP.HCM" },
  { key: "hai phong", label: "Hải Phòng" },
  { key: "hải phòng", label: "Hải Phòng" },
  { key: "da nang", label: "Đà Nẵng" },
  { key: "đà nẵng", label: "Đà Nẵng" },
  { key: "can tho", label: "Cần Thơ" },
  { key: "cần thơ", label: "Cần Thơ" },
  { key: "nha trang", label: "Nha Trang" },
  { key: "khanh hoa", label: "Khánh Hòa" },
  { key: "hue", label: "Huế" },
  { key: "huế", label: "Huế" },
  { key: "quang ninh", label: "Quảng Ninh" },
  { key: "ha long", label: "Hạ Long" },
  { key: "tu liem", label: "Hà Nội" },
  { key: "hoang mai", label: "Hà Nội" },
  { key: "thanh xuan", label: "Hà Nội" },
  { key: "cau giay", label: "Hà Nội" },
  { key: "long bien", label: "Hà Nội" },
  { key: "ba dinh", label: "Hà Nội" },
  { key: "thuong binh", label: "TP.HCM" },
  { key: "phu nhai", label: "TP.HCM" },
  { key: "binh duong", label: "Bình Dương" },
  { key: "thu dau", label: "Bình Dương" },
  { key: "dong nai", label: "Đồng Nai" },
  { key: "bien hoa", label: "Đồng Nai" },
  { key: "vung tau", label: "Vũng Tàu" },
  { key: "vũng tàu", label: "Vũng Tàu" },
  { key: "thuy van", label: "Vũng Tàu" },
  { key: "thùy vân", label: "Vũng Tàu" },
  { key: "quang ngai", label: "Quảng Ngãi" },
  { key: "quang nam", label: "Quảng Nam" },
  { key: "da nang", label: "Đà Nẵng" },
  { key: "ninh binh", label: "Ninh Bình" },
  { key: "thanh hoa", label: "Thanh Hóa" },
  { key: "nghe an", label: "Nghệ An" },
  { key: "vinh phuc", label: "Vĩnh Phúc" },
  { key: "hoa binh", label: "Hòa Bình" },
  { key: "phu tho", label: "Phú Thọ" },
  { key: "tuyen quang", label: "Tuyên Quang" },
  { key: "lang son", label: "Lạng Sơn" },
  { key: "quang tri", label: "Quảng Trị" },
  { key: "binh dinh", label: "Bình Định" },
  { key: "phu yen", label: "Phú Yên" },
  { key: "gia lai", label: "Gia Lai" },
  { key: "dak lak", label: "Đắk Lắk" },
  { key: "tay ninh", label: "Tây Ninh" },
  { key: "long an", label: "Long An" },
  { key: "tien giang", label: "Tiền Giang" },
  { key: "can tho", label: "Cần Thơ" },
  { key: "an giang", label: "An Giang" },
  { key: "kien giang", label: "Kiên Giang" },
  { key: "ca mau", label: "Cà Mau" },
  { key: "soctrang", label: "Sóc Trăng" },
  { key: "ha tinh", label: "Hà Tĩnh" },
  { key: "ha tĩnh", label: "Hà Tĩnh" },
  { key: "bac ninh", label: "Bắc Ninh" },
  { key: "bac giang", label: "Bắc Giang" },
  { key: "thai nguyen", label: "Thái Nguyên" },
  { key: "thái nguyên", label: "Thái Nguyên" },
  { key: "lam dong", label: "Lâm Đồng" },
  { key: "lâm đồng", label: "Lâm Đồng" },
  { key: "da lat", label: "Lâm Đồng" },
  { key: "ninh hinh", label: "Ninh Bình" },
  { key: "halong", label: "Hạ Long" },
  { key: "hạ long", label: "Hạ Long" },
  { key: "tu nghe", label: "Hải Phòng" },
  { key: "phu tho", label: "Phú Thọ" },
  { key: "vinh", label: "Nghệ An" },
  { key: "thanh hoá", label: "Thanh Hóa" },
  { key: "sapa", label: "Lào Cai" },
  { key: "lao cai", label: "Lào Cai" },
  { key: "cao bang", label: "Cao Bằng" },
  { key: "bắc giang", label: "Bắc Giang" },
  { key: "ha giang", label: "Hà Giang" },
  { key: "son la", label: "Sơn La" },
  { key: "lai chau", label: "Lai Châu" },
  { key: "dien bien", label: "Điện Biên" },
  { key: "yen bai", label: "Yên Bái" },
  { key: "hoa binh", label: "Hòa Bình" },
  { key: "hoa binh", label: "Hòa Bình" },
  { key: "bac kan", label: "Bắc Kạn" },
  { key: "bac kan", label: "Bắc Kạn" },
  { key: "vung tau", label: "Vũng Tàu" },
  { key: "bà rịa", label: "Bà Rịa" },
  { key: "bà rịa", label: "Bà Rịa" },
  { key: "phu yen", label: "Phú Yên" },
  { key: "dak nong", label: "Đắk Nông" },
  { key: "kon tum", label: "Kon Tum" },
  { key: "ben tre", label: "Bến Tre" },
  { key: "tra vinh", label: "Trà Vinh" },
  { key: "vinh long", label: "Vĩnh Long" },
  { key: "bac lieu", label: "Bạc Liêu" },
  { key: "cau mau", label: "Cà Mau" },
  { key: "dau giay", label: "TP.HCM" },
  { key: "phuoc long", label: "TP.HCM" },
  { key: "ninh hien", label: "Nha Trang" },
  { key: "vinh yen", label: "Vĩnh Phúc" },
  { key: "vinh phuc", label: "Vĩnh Phúc" },
  { key: "thanh hoa", label: "Thanh Hóa" },
  { key: "quang tri", label: "Quảng Trị" },
  { key: "quang ngãi", label: "Quảng Ngãi" },
  { key: "gioi vang", label: "Quảng Bình" },
  { key: "quang binh", label: "Quảng Bình" },
  { key: "tu ky", label: "Hải Dương" },
  { key: "thanh ha", label: "Hải Dương" },
  { key: "cat hai", label: "Hải Phòng" },
  { key: "vung tau", label: "Vũng Tàu" },
  { key: "mien dong", label: "Đồng Nai" },
  { key: "gia lai", label: "Gia Lai" },
  { key: "ia riang", label: "Gia Lai" },
  { key: "hue", label: "Huế" },
  { key: "phu nhai", label: "TP.HCM" },
  { key: "phuoc hung", label: "TP.HCM" },
  { key: "phuoc long", label: "TP.HCM" },
  { key: "dai hoc", label: "TP.HCM" },
  { key: "binh thanh", label: "TP.HCM" },
  { key: "cho lon", label: "TP.HCM" },
  { key: "tan phuoc", label: "TP.HCM" },
  { key: "go vap", label: "TP.HCM" },
  { key: "airport", label: "TP.HCM" },
  { key: "quang ngai", label: "Quảng Ngãi" },
  { key: "mien trung", label: "Miền Trung" },
  { key: "mien bac", label: "Miền Bắc" },
  { key: "mien nam", label: "Miền Nam" },
];

// Bỏ dấu tiếng Việt để so khớp: khách gõ "Cầu Giấy" hay "Cau Giay" đều nhận ra
export function norm(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d");
}

// Nhận diện tỉnh/thành từ nội dung tin. Trả về null nếu không khớp.
export function detectProvince(text: string): string | null {
  const lower = norm(text);
  let best: { label: string; len: number } | null = null;

  for (const { key, label } of ALIASES) {
    const k = norm(key);
    if (lower.includes(k) && (!best || k.length > best.len)) {
      best = { label, len: k.length };
    }
  }

  return best?.label ?? null;
}

// Tên hiển thị an toàn khi không xác định được tỉnh
export function provinceLabel(detected: string | null): string {
  return detected ?? "Khu vực của bạn";
}
