import { NextRequest,NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { adminClient } from "@/lib/admin";
import { getRadar,getRadarAreas } from "@/lib/radar/data";
import { validateRadarInput } from "@/lib/radar/criteria";
export const runtime="nodejs";
async function uid(){const s=await createClient();const {data:{user}}=await s.auth.getUser();return user?.id??null;}
export async function GET(_req:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await uid();if(!user)return NextResponse.json({error:"Cần đăng nhập"},{status:401});const r=await getRadar(adminClient(),user,(await params).id);if(!r)return NextResponse.json({error:"Không tìm thấy Radar."},{status:404});return NextResponse.json({radar:r});}
export async function PATCH(req:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await uid();if(!user)return NextResponse.json({error:"Cần đăng nhập"},{status:401});const id=(await params).id;const existing=await getRadar(adminClient(),user,id);if(!existing)return NextResponse.json({error:"Không tìm thấy Radar."},{status:404});const body=await req.json().catch(()=>({}));const has=(k:string)=>Object.prototype.hasOwnProperty.call(body,k);const v=validateRadarInput({name:has("name")?body.name:existing.name,areaV2:has("areaV2")?body.areaV2:existing.areaV2,categoryCode:has("categoryCode")?body.categoryCode:existing.categoryCode,priceMinVnd:has("priceMinVnd")?body.priceMinVnd:existing.priceMinVnd,priceMaxVnd:has("priceMaxVnd")?body.priceMaxVnd:existing.priceMaxVnd,areaMinM2:has("areaMinM2")?body.areaMinM2:existing.areaMinM2,areaMaxM2:has("areaMaxM2")?body.areaMaxM2:existing.areaMaxM2,minScore:has("minScore")?body.minScore:existing.minScore,dealTypes:has("dealTypes")?body.dealTypes:existing.dealTypes,ngoPOnly:has("ngoPOnly")?body.ngoPOnly:existing.ngoPOnly,status:has("status")?body.status:existing.status});if(!v.ok||!v.value)return NextResponse.json({error:"Dữ liệu Radar chưa hợp lệ.",fieldErrors:v.errors},{status:400});const admin=adminClient();const area=(await getRadarAreas(admin)).find(x=>x.areaV2===v.value!.areaV2);if(!area)return NextResponse.json({error:"Khu vực không còn trong dữ liệu CheckBDS."},{status:400});const {error}=await admin.from("radars").update({name:v.value.name,area_v2:area.areaV2,area_name:area.areaName,region_name:area.regionName,category_code:v.value.categoryCode,price_min_vnd:v.value.priceMinVnd,price_max_vnd:v.value.priceMaxVnd,area_min_m2:v.value.areaMinM2,area_max_m2:v.value.areaMaxM2,min_score:v.value.minScore,deal_types:v.value.dealTypes,ngop_only:v.value.ngoPOnly,status:v.value.status,updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",user);if(error)return NextResponse.json({error:"Không lưu được Radar."},{status:500});return NextResponse.json({ok:true,id});}
export async function DELETE(_req:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await uid();if(!user)return NextResponse.json({error:"Cần đăng nhập"},{status:401});const {error}=await adminClient().from("radars").delete().eq("id",(await params).id).eq("user_id",user);if(error)return NextResponse.json({error:"Không xoá được Radar."},{status:500});return NextResponse.json({ok:true});}