import type { SupabaseClient } from "@supabase/supabase-js";
import { confidenceFrom, MIN_SAMPLE_SIZE } from "@/lib/price/stats";
import type { PriceConfidence } from "@/lib/price/types";
import { listingMatchesCriteria } from "./criteria";
import type { RadarAreaOption,RadarComparison,RadarCriteria,RadarCoverage,RadarMatch,RadarSummary,Staleness } from "./types";

type Row=Record<string,any>;
const SOURCE="chotot_gateway";
const STALE_AFTER=24*60*60*1000;
function n(v:unknown):number|null{const x=typeof v==="number"?v:typeof v==="string"&&v.trim()?Number(v):null;return x!=null&&Number.isFinite(x)?x:null;}
function s(v:unknown):string|null{return typeof v==="string"&&v.trim()?v:null;}
function rel(iso:string|null){if(!iso)return null;const d=Math.max(0,Date.now()-new Date(iso).getTime()),m=Math.floor(d/60000);if(m<1)return"vừa xong";if(m<60)return m+" phút trước";const h=Math.floor(m/60);if(h<24)return h+" giờ trước";return Math.floor(h/24)+" ngày trước";}
function stale(iso:string|null):Staleness{if(!iso)return"unknown";return Date.now()-new Date(iso).getTime()>STALE_AFTER?"stale":"fresh";}
function mapCoverage(r:Row):RadarCoverage{return{status:r.coverage_status??"unknown",lastSeenAt:s(r.last_seen_at),freshness:s(r.coverage_freshness),staleness:r.coverage_staleness??"unknown",listingCount:n(r.coverage_listing_count),checkedAt:s(r.checked_at),source:s(r.coverage_source)??SOURCE,description:s(r.coverage_description),excludedCount:n(r.excluded_count)};}
function mapRadar(r:Row):RadarSummary{return{id:String(r.id),name:String(r.name),areaV2:Number(r.area_v2),areaName:s(r.area_name),regionName:s(r.region_name),categoryCode:n(r.category_code),priceMinVnd:n(r.price_min_vnd),priceMaxVnd:n(r.price_max_vnd),areaMinM2:n(r.area_min_m2),areaMaxM2:n(r.area_max_m2),minScore:n(r.min_score),dealTypes:Array.isArray(r.deal_types)?r.deal_types:[],ngoPOnly:Boolean(r.ngop_only),status:r.status==="PAUSED"?"PAUSED":"ACTIVE",createdAt:String(r.created_at),updatedAt:String(r.updated_at),coverage:mapCoverage(r),newMatchCount:Number(r.new_match_count??0),lastScanCount:n(r.last_scan_count),lastScanError:s(r.last_scan_error)};}

export async function getRadar(admin:SupabaseClient,userId:string,id:string){const {data,error}=await admin.from("radars").select("*").eq("id",id).eq("user_id",userId).maybeSingle();if(error)throw error;return data?mapRadar(data):null;}
export async function listRadars(admin:SupabaseClient,userId:string){const {data,error}=await admin.from("radars").select("*").eq("user_id",userId).order("updated_at",{ascending:false});if(error)throw error;return(data??[]).map(mapRadar);}
export async function getRadarAreas(admin:SupabaseClient):Promise<RadarAreaOption[]>{const {data,error}=await admin.from("market_listings").select("area_v2,area_name,region_name").not("area_v2","is",null).not("region_name","is",null).limit(5000);if(error)throw error;const seen=new Map<number,RadarAreaOption>();for(const r of data??[]){const a=n(r.area_v2),an=s(r.area_name),rn=s(r.region_name);if(a!=null&&an&&rn&&!seen.has(a))seen.set(a,{areaV2:a,areaName:an,regionName:rn});}return[...seen.values()].sort((a,b)=>a.regionName.localeCompare(b.regionName,"vi")||a.areaName.localeCompare(b.areaName,"vi"));}
export async function getAreaCoverage(admin:SupabaseClient,areaV2:number):Promise<RadarCoverage>{const [all,eligible,latest]=await Promise.all([
 admin.from("market_listings").select("id",{count:"exact",head:true}).eq("area_v2",areaV2),
 admin.from("market_listings").select("id",{count:"exact",head:true}).eq("area_v2",areaV2).eq("is_rent",false).eq("is_promoted",false).eq("is_price_valid",true),
 admin.from("market_listings").select("last_seen_at,area_name,region_name").eq("area_v2",areaV2).eq("is_rent",false).eq("is_promoted",false).eq("is_price_valid",true).order("last_seen_at",{ascending:false}).limit(1)
]);if(all.error||eligible.error||latest.error)throw all.error??eligible.error??latest.error;const count=eligible.count??0;const last=s(latest.data?.[0]?.last_seen_at);return{status:count===0?"none":count<MIN_SAMPLE_SIZE?"thin":"ok",lastSeenAt:last,freshness:rel(last),staleness:stale(last),listingCount:count,checkedAt:null,source:SOURCE,description:s(latest.data?.[0]?.area_name)?String(latest.data![0].area_name)+", "+String(latest.data![0].region_name??"Khu vực"):null,excludedCount:Math.max(0,(all.count??0)-count)};}

function pickStats(rows:Row[],size:number|null,rooms:number|null){if(size==null)return null;return rows.filter(r=>n(r.median_ppm2)!=null&&Number(r.trimmed_size??0)>=MIN_SAMPLE_SIZE).filter(r=>(n(r.size_min_m2)==null||size>=n(r.size_min_m2)!)&&(n(r.size_max_m2)==null||size<=n(r.size_max_m2)!)).sort((a,b)=>{const ar=rooms!=null&&n(a.rooms)===rooms?0:1,br=rooms!=null&&n(b.rooms)===rooms?0:1;if(ar!==br)return ar-br;return((n(a.size_max_m2)??1e9)-(n(a.size_min_m2)??0))-((n(b.size_max_m2)??1e9)-(n(b.size_min_m2)??0));})[0]??null;}
function comparison(stats:Row|null,ppm2:number|null):RadarComparison|null{if(!stats||ppm2==null)return null;const median=n(stats.median_ppm2);if(median==null)return null;return{medianPpm2:median,differencePercent:Math.round(((ppm2-median)/median)*1000)/10,confidence:confidenceFrom({scopeLevel:String(stats.scope_level) as "ward"|"district"|"province",trimmed:Number(stats.trimmed_size??0)}) as PriceConfidence,scopeDescription:s(stats.scope_description)};}
async function statsFor(admin:SupabaseClient,radar:RadarCriteria){if(radar.categoryCode==null)return[];const d=await admin.from("market_price_stats").select("scope_key,scope_level,scope_description,area_name,region_name,category_code,size_min_m2,size_max_m2,rooms,trimmed_size,median_ppm2").eq("scope_level","district").like("scope_key","district:"+radar.areaV2+"|cat:"+radar.categoryCode+"|size:%").order("stat_date",{ascending:false}).limit(200);if(!d.error&&(d.data??[]).some(r=>n(r.median_ppm2)!=null))return d.data??[];if(!radar.regionName)return[];const p=await admin.from("market_price_stats").select("scope_key,scope_level,scope_description,area_name,region_name,category_code,size_min_m2,size_max_m2,rooms,trimmed_size,median_ppm2").eq("scope_level","province").eq("region_name",radar.regionName).eq("category_code",radar.categoryCode).order("stat_date",{ascending:false}).limit(200);return p.data??[];}
function mapMatch(r:Row,c:RadarCriteria):RadarMatch{return{externalId:String(r.external_id),url:s(r.url),title:s(r.title),areaName:s(r.area_name),regionName:s(r.region_name),categoryCode:n(r.category_code),priceVnd:n(r.price_vnd),sizeM2:n(r.size_m2),pricePerM2:n(r.price_per_m2),listedAt:s(r.listed_at),lastSeenAt:s(r.last_seen_at),score:n(r.score),dealType:s(r.deal_type),isNgoP:n(r.is_ngop),scoringAvailable:Boolean(r.scoring_available),comparison:n(r.median_ppm2)!=null?{medianPpm2:n(r.median_ppm2),differencePercent:n(r.difference_percent),confidence:(s(r.confidence) as PriceConfidence|null),scopeDescription:s(r.scope_description)}:null,firstMatchedAt:String(r.first_matched_at),lastMatchedAt:String(r.last_matched_at),currentMatch:listingMatchesCriteria({categoryCode:n(r.category_code),priceVnd:n(r.price_vnd),sizeM2:n(r.size_m2)},c)};}

export async function scanRadar(admin:SupabaseClient,radar:RadarSummary){
 const previous=radar.coverage.checkedAt;const scanAt=new Date().toISOString();
 const q=admin.from("market_listings").select("external_id,url,title,area_name,region_name,category_code,price_vnd,size_m2,price_per_m2,listed_at,last_seen_at,rooms").eq("area_v2",radar.areaV2).eq("is_rent",false).eq("is_promoted",false).eq("is_price_valid",true).order("last_seen_at",{ascending:false}).limit(1000);
 if(radar.categoryCode!=null)q.eq("category_code",radar.categoryCode);if(radar.priceMinVnd!=null)q.gte("price_vnd",radar.priceMinVnd);if(radar.priceMaxVnd!=null)q.lte("price_vnd",radar.priceMaxVnd);if(radar.areaMinM2!=null)q.gte("size_m2",radar.areaMinM2);if(radar.areaMaxM2!=null)q.lte("size_m2",radar.areaMaxM2);
 const [matchRes,coverage,stats]=await Promise.all([q,getAreaCoverage(admin,radar.areaV2),statsFor(admin,radar)]);if(matchRes.error)throw matchRes.error;const rows=matchRes.data??[];
 const ids=rows.map(r=>String(r.external_id));let existingRows:Row[]=[];if(ids.length){const e=await admin.from("radar_matches").select("external_id,first_matched_at").eq("radar_id",radar.id).in("external_id",ids);if(e.error)throw e.error;existingRows=e.data??[];}
 const existing=new Map(existingRows.map(r=>[String(r.external_id),String(r.first_matched_at)]));let newCount=0;
 const mapped=rows.map(r=>{const id=String(r.external_id),ppm=n(r.price_per_m2),cmp=comparison(pickStats(stats,n(r.size_m2),n(r.rooms)),ppm);if(!existing.has(id))newCount++;return{radar_id:radar.id,external_id:id,url:s(r.url),title:s(r.title),area_name:s(r.area_name),region_name:s(r.region_name),category_code:n(r.category_code),price_vnd:n(r.price_vnd),size_m2:n(r.size_m2),price_per_m2:ppm,listed_at:s(r.listed_at),last_seen_at:s(r.last_seen_at),score:null,deal_type:null,is_ngop:null,scoring_available:false,median_ppm2:cmp?.medianPpm2??null,difference_percent:cmp?.differencePercent??null,confidence:cmp?.confidence??null,scope_description:cmp?.scopeDescription??null,first_matched_at:existing.get(id)??scanAt,last_matched_at:scanAt};});
 if(mapped.length){const u=await admin.from("radar_matches").upsert(mapped,{onConflict:"radar_id,external_id"});if(u.error)throw u.error;}
 const finalCoverage={...coverage,checkedAt:scanAt};
 const u=await admin.from("radars").update({checked_at:scanAt,last_seen_at:coverage.lastSeenAt,new_match_count:newCount,coverage_status:coverage.status,coverage_listing_count:coverage.listingCount,coverage_freshness:coverage.freshness,coverage_staleness:coverage.staleness,coverage_source:coverage.source,coverage_description:coverage.description,excluded_count:coverage.excludedCount,last_scan_count:rows.length,last_scan_error:null,updated_at:scanAt}).eq("id",radar.id);if(u.error)throw u.error;
 return{coverage:finalCoverage,matches:mapped.map(r=>mapMatch(r,radar)),newMatchCount:newCount};
}
export async function getRadarMatches(admin:SupabaseClient,radar:RadarSummary){const {data,error}=await admin.from("radar_matches").select("*").eq("radar_id",radar.id).order("last_matched_at",{ascending:false}).limit(100);if(error)throw error;return(data??[]).map(r=>mapMatch(r,radar));}
