-- P1 Price Intelligence V2 — bảng tra tên địa danh -> mã gateway.
-- Tách riêng khành 0015 để không sửa migration đã duyệt (0011-0014).
-- Idempotent, không đụng bảng checks, không đụng market_listings.
--
-- VÌ SAO CẦN:
-- Trước V2, tìm mã quận (area_v2) chỉ tra được từ market_listings — tức bảng
-- giá. Nhưng market_listings chỉ có dữ liệu SAU lần crawl giá đầu tiên, nên
-- một khu vực mới luôn rơi về tầng tỉnh, không bao giờ lên được tầng phường.
-- Vấn đề là tra cứu tên->mã bị giao cho một bảng sinh ra cho mục đích khác.
--
-- Bảng này là gazetteer đúng nghĩa: tên địa danh -> mã. Chỉ ghi khi ĐÃ xác nhận
-- khớp chính xác từ gateway. Không ghi khi không chắc chắn.
--
-- KHÔNG phải bảng giá: không có price, không có timestamp tin đăng.

create table if not exists public.geo_area_map (
  id           bigint generated by default as identity primary key,
  -- Tên đã CHUẨN HOÁ (bỏ dấu, lowercase, bỏ prefix hành chính) để so khớp
  -- tuyệt đối. Lưu bản chuẩn hoá giúp tránh phải chuẩn hoá lại ở mỗi lần đọc.
  region_name  text not null,
  area_name    text not null,
  region_v2    integer,
  area_v2      integer not null,
  resolved_at  timestamptz not null default now()
);

-- Một cặp (tỉnh, phường) chỉ có một mã. Chặn trùng để cache không nở ra.
create unique index if not exists geo_area_map_unique
  on public.geo_area_map (region_name, area_name);

comment on table public.geo_area_map is
  'Gazetteer ten dia danh -> ma gateway (area_v2/region_v2) cho Price Intelligence V2. Chi ghi khi da xac nhan khop chinh xac; null khong ghi. Doc/ghi chi qua service role.';

comment on column public.geo_area_map.region_name is
  'Ten tinh da chuan hoa (bo dau, lowercase, bo prefix hanh chinh).';
comment on column public.geo_area_map.area_name is
  'Ten phuong/xa da chuan hoa (bo dau, lowercase, bo prefix hanh chinh).';
comment on column public.geo_area_map.resolved_at is
  'Lan cuoi xac nhan ma nay dung voi gateway. De audit, khong dung lam cache TTL.';

-- RLS: KHONG tao policy nao.
--   authenticated / anon -> khong doc, khong ghi (khong co policy = khong duoc).
--   service_role -> bo qua RLS, dung duoc.
-- Day la bang tra cua server; client khong bao gio can doc truc tiep.
alter table public.geo_area_map enable row level security;

-- Bảng tra phụ trợ: dựng lại từ đầu cũng không mất dữ liệu người dùng.
-- Không thêm chính sách nào ở đây. Thêm = nới quyền, phải là change riêng.
